sudo: required
services:
  - docker

before_install:
  - docker build -t hrmtsngh18/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true hrmtsngh18/react-test npm run test

after_success:
  - docker build -t hrmtsngh18/multi-client ./client
  - docker build -t hrmtsngh18/multi-nginx ./nginx
  - docker build -t hrmtsngh18/multi-server ./server
  - docker build -t hrmtsngh18/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push hrmtsngh18/multi-client
  - docker push hrmtsngh18/multi-nginx
  - docker push hrmtsngh18/multi-server
  - docker push hrmtsngh18/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-a"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-866587856762"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"